"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def fibonacci(limit):
  prev, curr = 1, 2
  fiboSum = 2
  while True:
    prev, curr = curr, prev + curr
    if curr > limit:
      break
    if curr % 2 == 0:
      fiboSum += curr
  return fiboSum